name: Build and Deploy
on: [push]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}   
        - name: Install Packages
          run: npm install
        - name: Config Git
          run: |
            git config --global user.email "googerb@gmail.com"
            git config --global user.name "freeman-g"
            git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/freeman-g/react-tic-tac-toe.git
        - name: Deploy to GH Pages
          run: npm run deploy
        - name: Updating Domain
          run: echo "Update domain"
